### ISSUE TITLE
multimc - v0.6.8 - fix

### ISSUE THREAD

**Issue by omerakgoz34** [Calinou/scoop-games#100]
MultiMC is not v0.6.8 !
It's downloads v0.6.7 someway :/

**Comment by Calinou** [comment]
[The link definitely points to 0.6.8](https://github.com/Calinou/scoop-games/blob/df47ada9f9347ccaeb368c952647cd66a04809c1/bucket/multimc.json#L6). Maybe the developers forgot to update the version identifier before releasing 0.6.8? This occasionally happens in software development when people don't automate the version bumping process :wink:

**Comment by omerakgoz34** [comment]
@Calinou nop. scoop version is 0.6.7 and github "0.6.8" release is acually 0.6.7 but multimc.org download link downloads real 0.6.8 version :P

When i download with scoop, it installs 0.6.7 and multimc tells me new available stable update "0.6.8". I click "update" then multimc is updates itself and version is now 0.6.8 :D

That is not a problem but weird for scoop :p

**Comment by r15ch13** [comment]
The file from the website:
https://files.multimc.org/downloads/mmc-stable-win32.zip > `0.6.8-1419`

The file from Github release:
https://github.com/MultiMC/MultiMC5/releases/download/0.6.8/mmc-stable-win32.zip > `0.6.7-1375`

**Comment by comp500** [comment]
It's now updated to 0.6.11, it should work with the latest release on Github Releases now
