### ISSUE TITLE
[Bug]: dxvk extract location includes version number

### ISSUE THREAD

**Issue by krutomisi** [Calinou/scoop-games#1018]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

dxvk

### Expected/Current Behaviour

- The extracted files in the app folder include the version number, breaking direct linking to the files in the current folder
- I.E. a current install will place a file at the following locations

"scoop\apps\dxvk\2.2\dxvk-2.2\x64\d3d9.dll"
"scoop\apps\dxvk\current\dxvk-2.2\x64\d3d9.dll"

### Steps to Reproduce

```console
scoop install dxvk
```

### Possible Solution

extracted files could be moved up a folder
"\scoop\apps\dxvk\2.2\dxvk-2.2\x64\d3d9.dll"
to
"\scoop\apps\dxvk\2.2\x64\d3d9.dll"

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'games' bucket:
408ffd58 (HEAD -> master, origin/master, origin/HEAD) rpcs3: Update to version 0.0.29-15435
```

### Scoop Config

```console
last_update           : 8/4/2023 11:24:23 AM
use_external_7zip     : True (I am using NanaZip)
scoop_repo            : https://github.com/ScoopInstaller/Scoop
scoop_branch          : master
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      7.3.6
PSEdition                      Core
GitCommitId                    7.3.6
OS                             Microsoft Windows 10.0.22621
```

**Comment by RavenMacDaddy** [comment]
PR created. 

I'd encourage keeping an eye on the thread and the changes that were made to fix the issue – having the ability to fix your own problems is very satisfying.
