### ISSUE TITLE
[Bug]: Unable to Install/Update Citra & Citra-Canary

### ISSUE THREAD

**Issue by baltimoresports** [Calinou/scoop-games#1023]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

Citra-Canary

### Expected/Current Behaviour

When trying to install or upgrade Citra or Citra-Canary I receive the following error and it fails.

> Running the installer...
> Installing 'citra-canary' (2595-20230822) [64bit] from games bucket
> Loading citra-windows-msvc-20230822-f92693b.7z from cache
> Checking hash of citra-windows-msvc-20230822-f92693b.7z ... ok.
> Extracting citra-windows-msvc-20230822-f92693b.7z ... Could not find 'canary-mingw'! (error 16)
> At C:\Users\GamingPC\scoop\apps\scoop\current\lib\core.ps1:638 char:9
>          throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
>          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  CategoryInfo          : OperationStopped: (Could not find ...gw'! (error 16):String) [], RuntimeException
>  FullyQualifiedErrorId : Could not find 'canary-mingw'! (error 16)

### Steps to Reproduce

```console
scoop install citra-canary
```

### Possible Solution

Unable to fix issue

### Scoop and Buckets Version

```console
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
e4fb50618 (HEAD -> master, origin/master, origin/HEAD) teamviewer: Update to version 15.45.3

'games' bucket:
f776b049 (HEAD -> master, origin/master, origin/HEAD) rpcs3: Update to version 0.0.29-15518

'main' bucket:
4f37532e6 (HEAD -> master, origin/master, origin/HEAD) rakudo-star: Update to version 2023.08-01
```

### Scoop Config

```console
last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-08-22T08:34:00.5890862-04:00 master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
Name                           Value
----                           -----
PSVersion                      5.1.22621.1778
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22621.1778
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by otavio-silva** [comment]
Having the same issue

**Comment by baltimoresports** [comment]
Issue is now resolved. Thank you.

**Comment by Calinou** [comment]
- Fixed by https://github.com/Calinou/scoop-games/pull/1024.
