### ISSUE TITLE
[Bug]: Can't install trenchbroom, depends on missing extras/vcredist2015

### ISSUE THREAD

**Issue by TesseractCat** [Calinou/scoop-games#1066]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

trenchbroom

### Expected/Current Behaviour

Looks like a dependency for the `trenchbroom` package is no longer available, so it can't be installed.

### Steps to Reproduce

```console
PS> scoop install trenchbroom
Couldn't find manifest for 'vcredist2015'.
```

### Possible Solution

It looks like the `extras/vcredist2015` package was removed... I'm not sure if there was something specific about that version that this package required, but maybe it should change to one of the other available versions or be readded to extras.

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
e99f96617 (HEAD -> master, origin/master, origin/HEAD) openai-translator: Update to version 0.2.3

'games' bucket:
1d4e74bb6 (HEAD -> master, origin/master, origin/HEAD) rare: Update to version 1.10.4

'main' bucket:
79964353a (HEAD -> master, origin/master, origin/HEAD) texlab: Update to version 5.12.0

'nonportable' bucket:
ed77189 (HEAD -> master, origin/master, origin/HEAD) sandboxie-plus-np: Update to version 1.12.3

'versions' bucket:
55d0b5fec (HEAD -> master, origin/master, origin/HEAD) odin-nightly: Update to version 2023-12-03
```

### Scoop Config

```console
PS> scoop config

last_update                       scoop_branch scoop_repo
-----------                       ------------ ----------
2023-12-03T19:52:38.3540051-05:00 master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.18362.1171
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.18362.1171
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by Calinou** [comment]
As far as I know, recent vcredist versions are backwards-compatible to 2015, so it should be possible to install `extras/vcredist2022` to satisfy this dependency. Doing so requires modifying all manifests that currently depend on `vcredist2015` though.
