### ISSUE TITLE
freedoom@0.12.1: decompress error

### ISSUE THREAD

**Issue by Khoirulanami14** [Calinou/scoop-games#1067]
Running installer script...
dl_with_cache:
Line |
   6 |     dl_with_cache $app $version "$_" "$dir\$dlFile"
     |     ~~~~~~~~~~~~~
     | The term 'dl_with_cache' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR Exit code was 2!
Failed to extract files from C:\Users\User\scoop\apps\freedoom\0.12.1\dl.zip.
Log file:
  ~\scoop\apps\freedoom\0.12.1\7zip.log

**Comment by diefesson** [comment]
#1004 Seems related

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/Calinou/scoop-games/issues/876.
