### ISSUE TITLE
add DolphinTool.exe to dolphin stable now that it uses a not comically out of date version

### ISSUE THREAD

**Issue by BPplays** [Calinou/scoop-games#1182]
i made [a PR](https://github.com/Calinou/scoop-games/pull/1147) a bit ago to add DolphinTool.exe to beta and dev and i think it should be added to stable too with [the new versioning system](https://dolphin-emu.org/blog/2024/07/02/dolphin-releases-announcement/)

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by RuiNtD** [comment]
Working on this
