### ISSUE TITLE
[Request]: Replace chiaki4deck with chiaki-ng

### ISSUE THREAD

**Issue by Mahir007** [Calinou/scoop-games#1235]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used
- [X] A game or a game-related tool
- [X] English interface (or at least English documentation)
- [X] Latest stable or development version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

chiaki-ng

### Description

Next-Generation of Chiaki (the open-source remote play client for PlayStation)

### Homepage

https://github.com/streetpea/chiaki-ng

### Download Link(s)

https://github.com/streetpea/chiaki-ng/releases/download/v1.9.0/chiaki-ng-win_x64-VC-Release.zip

### Some Indication of Popularity/Repute

[chiaki-ng](https://streetpea.github.io/chiaki-ng/) is an open-source project (with 1.1k stars) serving as the next-generation of Chiaki with improvements and ongoing support now that the original Chiaki project is in maintenance mode only.

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:
