### ISSUE TITLE
minecraft@2.1.15376: hash check failed

### ISSUE THREAD

**Issue by acourtneybrown** [Calinou/scoop-games#128]
```
> scoop install minecraft
Installing 'minecraft' (2.1.15376) [64bit]
Minecraft.exe (2.8 MB) [======================================================================================] 100%
Checking hash of Minecraft.exe ... ERROR Hash check failed!
App:         games/minecraft
URL:         https://launcher.mojang.com/download/Minecraft.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    d9cdcf6fae6bd3ddc5c8a61b4453a75f5516b71e518ee3e410fa8df591940e70
Actual:      e6b10c53f5f7c501747e4ffb87a43a7a6cb60201866863531d96b4114aa2fb21
```

**Comment by Calinou** [comment]
cc @TheRandomLabs 

Maybe we should change it to `nightly` again to bypass the hash check.

**Comment by TheRandomLabs** [comment]
Yeah, I was hoping the version would update every time. Oh well.

>

**Comment by Calinou** [comment]
@TheRandomLabs Could you look into it, please?

**Comment by TheRandomLabs** [comment]
Yeah, if I can't figure out how to get the latest version, I'll just revert it.

**Comment by TheRandomLabs** [comment]
So I've found [another URL](https://bugs.mojang.com/rest/api/2/project/11101/versions) to check for the latest version in, but the latest version is still the same. It's a possibility that this is just a one-off, so maybe just fix the hash manually this time, and if it happens again, change the version back to `nightly`?
