### ISSUE TITLE
[Request]: Luanti (formerly Minetest)

### ISSUE THREAD

**Issue by TuritoYuenan** [Calinou/scoop-games#1293]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used
- [X] A game or a game-related tool
- [X] English interface (or at least English documentation)
- [X] Latest stable or development version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Luanti

### Description

An open source voxel game-creation platform with easy modding and game creation

### Homepage

https://www.luanti.org/

### Download Link(s)

https://github.com/minetest/minetest/releases/

### Some Indication of Popularity/Repute

Formerly known as Minetest (which is also in this bucket but outdated), its [repository](https://github.com/minetest/minetest) has nearly 11 thousand stars, more than 700 contributors, and the platform itself has a long-standing [Wikipedia page](https://wikipedia.org/wiki/Minetest).

A better solution might be to rename the existing `minetest` package to `luanti`.

**Comment by Calinou** [comment]
I would just rename the existing manifest to `luanti`. Feel free to open a PR for this 🙂

**Comment by TuritoYuenan** [comment]
OK, I have opened a PR. Though the download link might change in the future as the repo `minetest/minetest` hasn't been renamed.
