### ISSUE TITLE
SuperTuxKart: update to 1.1.0

### ISSUE THREAD

**Issue by 7wells** [Calinou/scoop-games#140]
Hello,

Would you mind updating STK to version 1.1.0? In "supertuxkart.json", there are still the 32 and 64bit versions 1.0. The new ones can be found there:

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.1/SuperTuxKart%201.1.0%20installer-64bit.exe/download
SHA1: 8276e52ab9a66d2884fbb53b1dbe9ee7b6a61555

https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.1/SuperTuxKart%201.1.0%20installer-32bit.exe/download
SHA1: c60e2b49df8386509f056c8cf711e27c5c3c129d

Thank you for your kind consideration.

PS:
There is even a 1.2 RC1 available:
https://sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.2-rc1/

**Comment by Calinou** [comment]
> PS:
> There is even a 1.2 RC1 available:
> sourceforge.net/projects/supertuxkart/files/SuperTuxKart/1.2-rc1

Note that this bucket only packages stable releases, unless the developers of a project make enough beta/development releases to warrant creating a separate `-dev` package.

**Comment by 7wells** [comment]
Again, thank you very much! 👍
