### ISSUE TITLE
Add a short description per game?

### ISSUE THREAD

**Issue by 7wells** [Calinou/scoop-games#141]
Hello,
Please forgive me if this is not the right place to ask for rather a feature than reporting an issue. Would it be possible and feasible to add short descriptions for the games? I know that one can open the json files, go to the included links and see what the game is about, but this is a little bit cumbersome. So is adding a short description per game (in the game bucket list) an option worth to consider? Or/and add a category like  'arcade', 'rpg', 'racer', 'shooter', etc.?

**Comment by Calinou** [comment]
You can see a list of apps here: https://rasa.github.io/scoop-directory/by-score#Calinou_scoop-games

**Comment by 7wells** [comment]
Oh, cool - thank you so much! 👍
