### ISSUE TITLE
rvgl load failed

### ISSUE THREAD

**Issue by 7wells** [Calinou/scoop-games#142]
Hello,

The link for rvgl in json reads:
`https://distribute.re-volt.io/releases/rvgl_full_win64a_online.zip`

The correct link is without the 'a':
`https://distribute.re-volt.io/releases/rvgl_full_win64_online.zip`
at least according to the releases folder:
https://distribute.re-volt.io/releases

Among others, there are:
rvgl_full_win64_basic.zip                          12-May-2020 21:58            77024973
rvgl_full_win64_online.zip                         22-Jun-2020 20:38          1432835780
rvgl_full_win64_original.zip                       12-May-2020 21:58           183547663

I am not affiliated with rvgl and have no clue how these versions differ from each other. And to make things even more complicated, there is yet another Win64 version linked directly in the landing page of the project (https://rvgl.re-volt.io):
https://rvgl.re-volt.io/downloads/rvgl_20.0430a_setup_win64.exe

Thank you so much for looking into this! 👍 

PS - Maybe the following question is somewhat OT here:

Is it possible for a scoop user to apply a temporary workaround for such dead links? I.e., can scoop users give the full download path for a game when doing 'scoop install'? Or is amending the json file (by the developer/contributor) the only really well working solution?

**Comment by Calinou** [comment]
> Is it possible for a scoop user to apply a temporary workaround for such dead links? I.e., can scoop users give the full download path for a game when doing 'scoop install'? Or is amending the json file (by the developer/contributor) the only really well working solution?

As far as I know, you can't override the download path.
