### ISSUE TITLE
Minecraft Launcher installation broken

### ISSUE THREAD

**Issue by RaphaelTarita** [Calinou/scoop-games#146]
This issue concerns the "minecraft@2.1.16101" app.

I have noticed some time ago that the minecraft launcher installation made by scoop is somehow broken. I've tested it on two different machines and across some versions of the app, but whenever I install minecraft via `scoop install minecraft`. the resulting launcher executable cannot be launched; instead I get the error "Unable to update the Minecraft Native Launcher". Googling this error message yields several results, which all somehow suggest re-installing your launcher installation (Example: https://www.auslogics.com/en/articles/fix-unable-to-update-minecraft-native-launcher/). Uninstalling and re-installing minecraft via scoop does not resolve the issue, however. For now, the only solution that I found was to `scoop uninstall minecraft` and then download the installer directly from the minecraft homepage. 

I'd be happy if I could keep managing all my apps, including minecraft, with scoop.

I tried this using Windows 10.

**Comment by Calinou** [comment]
cc @TheRandomLabs @adambriny

**Comment by TheRandomLabs** [comment]
Looks like the launcher no longer likes the persist shims. We'll have to manually copy from and to the persist folders now.

**Comment by Calinou** [comment]
@TheRandomLabs Can you look into opening a pull request for this, please? Thanks in advance :slightly_smiling_face:

**Comment by TheRandomLabs** [comment]
Sure, I'll get on it when I can.
