### ISSUE TITLE
[Request] Add TripleA (json file proposal provided)

### ISSUE THREAD

**Issue by 7wells** [Calinou/scoop-games#152]
Hello,

Would you please consider adding TripleA?
https://triplea-game.org

https://github.com/triplea-game/triplea/releases/download/2.2.20868/TripleA_2.2.20868_windows-64bit.exe
https://github.com/triplea-game/triplea/releases/download/2.2.20868/TripleA_2.2.20868_windows-32bit.exe

SHA256 hashes:
3e5ab1eff14a2bffe8bce2898a3c6d4a79851e29ad2421865786d340cdc1d7cb  TripleA_2.2.20868_windows-32bit.exe
467f0351fb57dfa45b4763698d66faac824c064d3275077903434ea6455d5634  TripleA_2.2.20868_windows-64bit.exe

Release tag (number changes, though):
https://github.com/triplea-game/triplea/releases/tag/2.2.20868

List of pre-releases:
https://github.com/triplea-game/triplea/releases
I would prefer that scoop installs the latest release, not pre-release, if you do not mind.

Since I do not (yet) know if I am allowed to do a pull request and do not know how I would do it, please see below my first try on a json file:
```
{
    "homepage": "https://triplea-game.org/",
    "description": "Turn-based free and open-source strategy game based on the Axis & Allies board game",
    "version": "2.2.20868",
    "license": "GNU General Public License v3.0 with additional permissions",
    "url": "https://github.com/triplea-game/triplea/releases/download/2.2.20868/TripleA_2.2.20868_windows-64bit.exe",
    "hash": "3e5ab1eff14a2bffe8bce2898a3c6d4a79851e29ad2421865786d340cdc1d7cb",
    "shortcuts": [
        [
            "TripleA.exe",
            "TripleA"
        ]
    ],
    "checkver": {
        "url": "https://triplea-game.org/download",
        "regex": "TripleA_([\\d.]+)_windows-64bit.exe"
		
    }
}
```

I used wesnoth as an example but removed the autoupdate code, as I do not understand how that works. But I am willing to learn. :) How can I test all this? Thank you for your patience and help!

**Comment by Calinou** [comment]
> How can I test all this? Thank you for your patience and help!

Save your json file as `triplea.json` then run `scoop install triplea.json` in the folder where the JSON file is located.

**Comment by 7wells** [comment]
This works* for 64bit (I could not test it for 32bit), but it lacks `checkver` and `autoupdate`:
```
{
    "homepage": "https://triplea-game.org/",
    "description": "Turn-based free and open-source strategy game based on the Axis & Allies board game",
    "version": "2.2.20868",
    "license": "GNU General Public License v3.0 with additional permissions",
    "architecture": {
        "64bit": {
            "url": "https://github.com/triplea-game/triplea/releases/download/2.2.20868/TripleA_2.2.20868_windows-64bit.exe",
            "hash": "467f0351fb57dfa45b4763698d66faac824c064d3275077903434ea6455d5634"
        },
        "32bit": {
            "url": "https://github.com/triplea-game/triplea/releases/download/2.2.20868/TripleA_2.2.20868_windows-32bit.exe",
            "hash": "3e5ab1eff14a2bffe8bce2898a3c6d4a79851e29ad2421865786d340cdc1d7cb"
        }
	},
    "shortcuts": [
        [
            "TripleA.exe",
            "TripleA"
        ]
    ],
}
```

*There is this error message at the end, but I assume that this is, because it is not yet officially implemented, right?
```
Linking ~\scoop\apps\triplea\current => ~\scoop\apps\triplea\2.2.20868
Creating shortcut for TripleA (TripleA.exe) failed: Couldn't find C:\Users\user\scoop\apps\triplea\current\TripleA.exe
```

**Comment by 7wells** [comment]
install.json looks like this (different than e.g. for rvgl), so I assume that this also needs more attention:
```
{
    "architecture": "64bit",
    "url": "C:\\Users\\master\\scoop\\triplea.json"
}
```

**Comment by Calinou** [comment]
> This works* for 64bit (I could not test it for 32bit), but it lacks checkver and autoupdate:

To test 32-bit, use `scoop install -arch 32bit triplea.json` instead.

**Comment by 7wells** [comment]
Uiversal Extractor 2 says:
```
------------------ Exeinfo PE ------------------

 install4j x64 Multi-Platform Edition [ v5.x - 6.x ] - www.ej-technologies.com -  stub:  Microsoft Visual C++ v9.0 - 200x - ( x64 ) microsoft.com (exe 4883ec 28-48) - no sec. CAB/7z/Zip - Name : TripleA. - ovl : install4j / exe4j  Runtime DATA - www.ej-technologies.com

( Java installer builder ) try : internal BIN Archives Ripper ( zip/lzma )   ovl ... start bytes xor88 .pack - Java class packed file

------------------ PEiD (ext) ------------------

Not a valid PE file

----------------- PEiD (hard) -----------------

Not a valid PE file

--------------------- TrID ---------------------

 56.1% (.EXE) InstallShield setup (43053/19/16)
 36.0% (.EXE) Win64 Executable (generic) (27624/17/4)

---------------- Unix File Tool ----------------

PE32+ executable for MS Windows (GUI) Mono/.Net assembly

------------------ MediaInfo ------------------


[General]
Format                  MZ
Format profile          Executable / AMD x86-64
File size               60.1 MiB
Encoded date            UTC 2020-03-03 22:39:07
```
So I am not sure why kind of installer this is.

**Comment by 7wells** [comment]
Universal Extractor 2 (from bioruebe) can extract it without errors. I left some files and folders out to reduce the output:
```
│   tree.txt
│   triplea-root
│   TripleA.exe
│   uninstall.exe
│   
├───assets
    
├───bin
│       triplea-game-headed-2.2.20868.jar
│       
└───install4j
        i4jdel.exe
        i4jinst.dll
```
