### ISSUE TITLE
Consider to contribute to winget packages

### ISSUE THREAD

**Issue by Croydon** [Calinou/scoop-games#169]
I hope that this question / suggestion does not seem disrespectful. Every work which makes it easier to use open source software is awesome. Thank you for your work!

That said, maybe it is a more effective use of time to contribute to winget packages going forward.

Like scoop, winget is a package manager for Windows. The huge difference is, that winget is from Microsoft and will be the official Windows package manager, which is going to be installed by default on all Windows 10 computers once it hits version 1.0

Winget is open source too: https://github.com/microsoft/winget-cli

Winget does support several connected repositories / sources for packages with the official one being https://github.com/microsoft/winget-pkgs

Having a random look in the manifest, there are already several open source games in it, like:
  * https://github.com/microsoft/winget-pkgs/tree/master/manifests/WildfireGames/0AD
  * https://github.com/microsoft/winget-pkgs/tree/master/manifests/Aardappel
  * https://github.com/microsoft/winget-pkgs/tree/master/manifests/FreeCiv/FreeCiv
  * https://github.com/microsoft/winget-pkgs/tree/master/manifests/OpenTTD/OpenTTD

and probably many more.

Adding new packages or package versions does not seem to be complicated and works via pull requests.

I would love to know what you think 😄

**Comment by Calinou** [comment]
I've already started contributing to WinGet when it was just introduced: https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3ACalinou+

That said, ZIP file support is missing in WinGet. This means we can't package most applications in this bucket in WinGet yet: https://github.com/microsoft/winget-cli/issues/140

**Comment by Croydon** [comment]
Thanks for the pointers! I wasn't aware of the zip limitation
