### ISSUE TITLE
mgba-dev not updating

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#174]
I was checking at the emulator's website beforehand; https://mgba.io/downloads.html

Right now the Scoop build is at nightly-20201115 while the official dev build is seemingly updated daily, including today 201206.

Thanks in advance

**Comment by Calinou** [comment]
mgba-dev now has a `nightly` version, as the build is continuously updated without its URL changing. This means the hash is broken every day, and using the `nightly` version identifier is the best way to handle this with Scoop. (`nightly` has special treatment in Scoop and doesn't require hash verification.)

You need to uninstall mgba-dev and reinstall it. This is a Scoop limitation.
