### ISSUE TITLE
Steam - Fatal Error

### ISSUE THREAD

**Issue by NatoBoram** [Calinou/scoop-games#18]
Hi! I tried to install Steam using `scoop`, but I've ran into an issue.

First, it gets stuck there : 

![Updating Steam](https://user-images.githubusercontent.com/10495562/55698346-5acd9d80-5993-11e9-8f57-5d16dcc22d55.PNG)

After a few minutes, there's this error : 

![Fatal Error](https://user-images.githubusercontent.com/10495562/55698359-68832300-5993-11e9-9608-6be59e8db876.PNG)

I also tried to run Steam's installer over the `current` folder just to see what happens, and I got the same issue. Probably a problem on Steam's part, but I'd like to see if you have any idea of how to get around this.

**Comment by NatoBoram** [comment]
Okay, so I've ran Steam's uninstaller, uninstalled via scoop, then re-installed it via scoop. Now it works.

Strange stuff :/

**Comment by Calinou** [comment]
Steam comes from the `scoop-extras` bucket anyway, not `scoop-games` :wink:

**Comment by NatoBoram** [comment]
… oops! Sorry for that!
