### ISSUE TITLE
[Request] Add DuckStation

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#185]
Hello

Is it possible to add the PSX emulator found here: https://github.com/stenzek/duckstation

Thank you

**Comment by Calinou** [comment]
Sure, feel free to open a pull request for it :slightly_smiling_face:

**Comment by RavenMacDaddy** [comment]
Absolutely, will do.

**Comment by RavenMacDaddy** [comment]
I tried to figure it out by comparing with JSONs like Citra-canary and Dolphin, but sadly I can't figure it out completely.

Hopefully someone smarter than me knows how to do it properly.
