### ISSUE TITLE
brogue@1.7.5: Download failed

### ISSUE THREAD

**Issue by yuuki76** [Calinou/scoop-games#199]
The remote server returned an error: (404) Not Found.

**Comment by Calinou** [comment]
[It seems the game's downloads have moved to Google Drive.](https://sites.google.com/site/broguegame). I'm not sure if I can do anything about this, as Google Drive is difficult to download files in an unattended manner from.

**Comment by BlackPowerade** [comment]
The original brogue is now deprecated and superseded by the community edition. https://github.com/tmewett/BrogueCE
The original author also recommends the community edition over the original. https://sites.google.com/site/broguegame

> For the most current version of Brogue, please look to the Brogue Community Edition site, instead of the version listed below. Brogue CE includes many enhancements and bugfixes that improve the game beyond the older version linked below. Many thanks to @tmewett for launching and maintaining Brogue CE, and to the many talented contributors to the project.

I'm working on making a manifest to replace the original brogue.
