### ISSUE TITLE
Request for DOOM Retro Package

### ISSUE THREAD

**Issue by kewalsky** [Calinou/scoop-games#209]
hey! looking to see if a doom retro manifest could be added in

https://github.com/bradharding/doomretro

program is distributed in a zip and runs portable. persists would ideally be the folder "savegames", folder "screenshots" and file doomretro.cfg, all located in program's root folder

the wad picker defaults to the last folder it was given - due to that don't believe a wads directory would need to be persisted like in the gzdoom and chocolate doom manifests

**Comment by kewalsky** [comment]
also just to note the savegames/screenshots/doomretro.cfg file don't exist until first run

**Comment by Calinou** [comment]
Feel free to open a pull request for this 🙂
