### ISSUE TITLE
Add game save transfer between version of Dwarf Fortress

### ISSUE THREAD

**Issue by Rdna123** [Calinou/scoop-games#210]
It would be convenient to auto transfer saves between versions, like with a symbolic link or shortcut to a save folder outside save directory.

**Comment by Calinou** [comment]
Feel free to open a pull request to add a `persist` field to the manifest: [`bucket/dwarf-fortress.json`](https://github.com/Calinou/scoop-games/blob/master/bucket/dwarf-fortress.json)

I don't play Dwarf Fortress, so I wouldn't know which files/folders to add.

**Comment by Rdna123** [comment]
I will try, but I am not that experienced with scoop json files and json files in general but I will try.

**Comment by Rdna123** [comment]
Is there a way to make the executable to run from the directory it is from when using the command line

**Comment by Calinou** [comment]
> Is there a way to make the executable to run from the directory it is from when using the command line

This is possible, but not particularly convenient. As far as I know, you need to write a `.bat` file during installation and reference that `.bat` file in the manifest's `bin` entry.

**Comment by Rdna123** [comment]
Thanks
