### ISSUE TITLE
DOOM retro is using the config file in the apps dir instead of the persist dir

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#216]
Was making several changes to the config in the persist dir since I saw the config file there.

When starting the game again I noticed that none of the changes I had made were active.

Only when I copied the file to the apps directory the changes became active.

Thank you for your time.

Edit: I also found that all the keybindings at the bottom of the config are missing either in the one present in the persist dir, or the one that's present when downloaded and used currently in the apps dir. 

One way to restore those is to have no config present at all and DOOM retro will create one for you - then you can copy those bindings to your config.

Hopefully this can be solved in the manifest, but maybe that's simply a bug with the current version of DOOM Retro.

**Comment by Calinou** [comment]
cc @BlackPowerade

**Comment by BlackPowerade** [comment]
I can't replicate this.     
Changes made from `persist` mirror in `app` and vice versa.        
scoop is correctly hardlinking `doomretro.cfg` in `persist` and `app`    
Here are two images of the `doomretro.cfg` date modified, before and after first run.  
![image](https://user-images.githubusercontent.com/21957509/110225158-d138ea00-7e9f-11eb-8360-6022e4fca556.png)
![image](https://user-images.githubusercontent.com/21957509/110225178-00e7f200-7ea0-11eb-8f3e-8a53c8d3268e.png)

**Comment by RavenMacDaddy** [comment]
Got the same result after reinstalling - thanks guys.
