### ISSUE TITLE
yquake2.json reverted to old version after PR

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#232]
I checked the app manifests information on how to make checkver/autoupdate include letters in the versions it checks for, sadly couldn't find that information.

After my PR to v7.45a the json has been reverted to the older version.

Is there some way to make checkver and autoupdate account for versions with letters in them and get the json back to the newer version?

**Comment by BlackPowerade** [comment]
You would need to use regex to ensure it only captures the last version instance on [https://deponie.yamagi.org/quake2/windows/]()     
The closest thing I have to working is this cursed thing:      
`quake2-(?<ver>[\d\.\d?(\w)]+).zip<\/a>(?![\s\S]*([\d\.\w]+)\.zip<\/a>)`      
and even still scoop can't determine the extra 'a' at the end to mean a new version, or it is still being tripped up by the multiple matches on the page.         
I'm not good enough at regex to solve this.

**Comment by RavenMacDaddy** [comment]
Currently not using letters in versioning - closing.
