### ISSUE TITLE
mame:  version 0.218 and newer are 64-bit only

### ISSUE THREAD

**Issue by Dabombber** [Calinou/scoop-games#244]
As of MAME 0.218, [32-bit Windows binaries are no longer supplied](https://www.mamedev.org/?p=479). The binary for the 64-bit version has also been renamed to simply "mame.exe".

I'm not sure if there's a way to limit versions by architecture or if it'd be better to move 32-bit versions to a legacy manifest.

**Comment by Calinou** [comment]
> I'm not sure if there's a way to limit versions by architecture or if it'd be better to move 32-bit versions to a legacy manifest.

There isn't, but I think supporting 64-bit only is fine as we move forward. The Scoop manifest can have a `64bit` architecture defined but not `32bit` for 64-bit only applications.
