### ISSUE TITLE
mameui - Nightly json does not seem to change hash

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#247]
Hello

Saw that my pull request was approved - appreciate that.

I did however test to see if the hash indeed changes every download, and that doesn't seem to be the case.

I tested a couple of downloads of the latest version, which at the time of writing is 231, and these are the results:

![image](https://user-images.githubusercontent.com/67732686/116821188-254b0c80-ab79-11eb-8d29-b409da294a5e.png)

Deleted the cache each time of course to initiate a new download, hash check always turns out okay.

Don't hesitate to get back to me if your results differ.

My latest json can be found [here](https://github.com/RavenMacDaddy/scoop-apps/blob/main/bucket/mameui.json) for reference.

**Comment by Calinou** [comment]
> I did however test to see if the hash indeed changes every download, and that doesn't seem to be the case.

I wasn't saying that the hash changed every download. Instead, the developer will occasionally update the release but will not change the file name accordingly. This makes it impossible for us to update the hash and the filename at the same time.

**Comment by RavenMacDaddy** [comment]
Ah, I understand, thank you for the explanation.

**Comment by RavenMacDaddy** [comment]
Out of curiosity, won't checkver make sure that even if the URL doesn't change, e.g. with a version in the file name, the versioning system of Scoop remains functioning - could you elaborate on that?
