### ISSUE TITLE
snes9x-dev@1.60-978: Download via aria2 failed

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#274]
Download failed! (Error 3) Resource was not found

Gonna check if downloads have been moved in some way.

EDIT: Indeed they've, I can't even access the main appveyor page in checkver anymore, and sadly I can't find anything through Google personally.

**Comment by NoraTheGamer** [comment]
Artifact expired that is the issue. Ill compile a copy and slap it here for you if you want

**Comment by RavenMacDaddy** [comment]
Sorry to hear that.

That would be great, thank you.

**Comment by RavenMacDaddy** [comment]
Development is up and running again and installs without issues through scoop, closing.
