### ISSUE TITLE
mgba-dev@7063-20210710: Shim creation fail

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#290]
Cannot shim 'mGBA.exe': File does not exist

I got "Copy-Item: Cannot find path 'D:\Backup\Scoop\apps\mgba-dev\7063-20210710\D:\Backup\Scoop\apps\mgba-dev\7063-20210710\mGBA-build-2021-07-10-win64-7063-3392f86dcbaf0c708e2513ca5bc3e76634459d6e' because it does not exist." so the script is currently going to drive root twice.

**Comment by BlackPowerade** [comment]
Can't reproduce.
Both latest `7065-20210711` and `7063-20210710` work fine on my end. There wasn't any change in mgba builds distribution between the two.
I'm not quite sure why it would fail to shim, my best guess is something going on with the file links.

**Comment by RavenMacDaddy** [comment]
Maybe something with me using a custom path breaks the dir part of the script.

**Comment by RavenMacDaddy** [comment]
This issue has been resolved, closing.
