### ISSUE TITLE
project64@3.0.1: hash check failed

### ISSUE THREAD

**Issue by Asmial** [Calinou/scoop-games#292]
Installing 'project64' (3.0.1) [64bit]
setup-project64-3-0-0-5632-f83bee9 (4,2 MB) [=================================================================] 100%
Checking hash of setup-project64-3-0-0-5632-f83bee9 ... ERROR Hash check failed!
App:         games/project64
URL:         https://www.pj64-emu.com/file/setup-project64-3-0-0-5632-f83bee9
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    591ae9fe2c073d452f8eb08cbe5a9705224f131eadeb553e270a50a11592fd11
Actual:      5892d6bef423076a103991c78690083a87536865ea848c0eccf2e4f94a64033b

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=project64%403.0.1%3a+hash+check+failed

**Comment by NoraTheGamer** [comment]
Cannot duplicate. This is invalid.

```PS C:\Users\Nora\scoop-games\bucket> scoop uninstall project64
Uninstalling 'project64' (3.0.1).
Removing shortcut ~\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Scoop Apps\Project64.lnk
Unlinking ~\scoop\apps\project64\current
'project64' was uninstalled.
PS C:\Users\Nora\scoop-games\bucket> scoop install project64
Installing 'project64' (3.0.1) [64bit]
Loading setup-project64-3-0-0-5632-f83bee9 from cache
Checking hash of setup-project64-3-0-0-5632-f83bee9 ... ok.
Extracting setup-project64-3-0-0-5632-f83bee9 ... done.
Linking ~\scoop\apps\project64\current => ~\scoop\apps\project64\3.0.1
Creating shortcut for Project64 (Project64.exe)
Persisting Config
Persisting Logs
Persisting Save
Persisting Screenshots
Persisting Textures
Persisting Games
Persisting ROMs
'project64' (3.0.1) was installed successfully!```
