### ISSUE TITLE
Add Ludo

### ISSUE THREAD

**Issue by SViN24** [Calinou/scoop-games#297]
Ludo is a work in progress libretro frontend written in go.

https://github.com/libretro/ludo

**Comment by ViCrack** [comment]
{
    "version": "0.16.18",
    "description": "A libretro frontend written in golang",
    "homepage": "https://github.com/libretro/ludo",
    "license": "GPL-3.0-or-later",
    "architecture": {
        "64bit": {
            "url": "https://github.com/libretro/ludo/releases/download/v0.16.18/Ludo-Windows-x86_64-0.16.18.zip",
            "hash": "7dc3e65b5a9f821429bd2326d756017aff62451f0a92313fc7bc2fba84f295c6",
            "extract_dir": "Ludo-Windows-x86_64-0.16.18",
            "shortcuts": [
                [
                    "ludo.exe",
                    "Ludo"
                ]
            ]
        }
    },
    "checkver": "github",
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/libretro/ludo/releases/download/v$version/Ludo-Windows-x86_64-$version.zip",
                "extract_dir": "Ludo-Windows-x86_64-$version"
            }
        }
    }
}
