### ISSUE TITLE
mednafen@1.27.1: base directory has changed

### ISSUE THREAD

**Issue by satorope** [Calinou/scoop-games#323]
Mednafen base directory has changed.
This wastes persistent data.

%USERPROFILE%\.mednafen

**Comment by satorope** [comment]
I understand.

**Comment by satorope** [comment]
I'm sorry, I understand the cause.
My PC set the environment variable HOME, which was specific to my environment.
There was no cause for scoop.

https://mednafen.github.io/documentation/

Mednafen's "base directory" is the directory under which Mednafen stores its data and looks for various auxiliary data by default. If the "HOME" environment variable is set, it will be suffixed with "/.mednafen" and used as the base directory(in other words ~/.mednafen, or $HOME/.mednafen). If the "MEDNAFEN_HOME" environment variable is set, it will be used as the base directory. If neither the "HOME" nor "MEDNAFEN_HOME" environment variable is set, and the current user has an entry in the password file, the corresponding home directory will be used as if it were the "HOME" environment variable.

On Microsoft Windows, these conditions are typically not met, in which case the directory the Mednafen executable("mednafen.exe") is in will be used as the base directory.

**Comment by beyondmeat** [comment]
@Calinou can close, @satorope
