### ISSUE TITLE
minecraft@java-edition: hash check failed

### ISSUE THREAD

**Issue by matthewbegun** [Calinou/scoop-games#34]
Attempting to install minecraft produced the following output (usernames have been changed) : 

PS C:\Users\foo> scoop install minecraft
WARN  Scoop uses 'aria2c' for multi-connection downloads.
WARN  Should it cause issues, run 'scoop config aria2-enabled false' to disable it.
Installing 'minecraft' (java-edition) [64bit]
Starting download with aria2 ...
Download: [#2704db 0B/0B CN:1 DL:0B]
Download: [#2704db 208KiB/2.0MiB(10%) CN:1 DL:213KiB ETA:8s]
Download: [#2704db 416KiB/2.0MiB(20%) CN:1 DL:210KiB ETA:7s]
Download: [#2704db 656KiB/2.0MiB(31%) CN:1 DL:218KiB ETA:6s]
Download: [#2704db 880KiB/2.0MiB(42%) CN:1 DL:222KiB ETA:5s]
Download: [#2704db 1.0MiB/2.0MiB(52%) CN:1 DL:218KiB ETA:4s]
Download: [#2704db 1.2MiB/2.0MiB(63%) CN:1 DL:217KiB ETA:3s]
Download: [#2704db 1.4MiB/2.0MiB(73%) CN:1 DL:218KiB ETA:2s]
Download: [#2704db 1.7MiB/2.0MiB(85%) CN:1 DL:221KiB ETA:1s]
Download: [#2704db 1.8MiB/2.0MiB(94%) CN:1 DL:216KiB]
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 2704db|OK  |   214KiB/s|C:/Users/foo/scoop/cache/minecraft#java-edition#https_launcher.mojang.com_download_Minecraft.exe
Download: Status Legend:
Download: (OK):download completed.
Checking hash of Minecraft.exe ... ERROR Hash check failed!
App:         games/minecraft
URL:         https://launcher.mojang.com/download/Minecraft.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    f391a3c42bd3cc19bf76cf62de164b263ee2a6e9b3994120c3c613fb30af7476
Actual:      b8e54a71ffc79bb9c95902f877dca7e1880b907ea94ff9659bb1a927808787a2

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=minecraft%40java-edition%3a+hash+check+failed

**Comment by Calinou** [comment]
Thanks for reporting it :slightly_smiling_face:
