### ISSUE TITLE
pcsx2-dev update and install error

### ISSUE THREAD

**Issue by ompadu** [Calinou/scoop-games#463]
It seems that pcsx2-dev update/install intermittently gets broken. The latest install error message:
```
Installing 'pcsx2-dev' (1.7.0-2014) [64bit]
Loading index.php from cache
Checking hash of index.php ... ok.
Extracting dl.7z ... Could not find 'pcsx2-v1.7.0-dev-2014-g86e12c9603-windows-x86'! (error 16)
At C:\Users\<username>\scoop\apps\scoop\current\lib\core.ps1:510 char:9
+         throw "Could not find '$(fname $from)'! (error $($proc.ExitCo ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...86'! (error 16):String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find 'pcsx2-v1.7.0-dev-2014-g86e12c9603-windows-x86'! (error 16)
```

Recent history of breakage and recovery can be found in this initial [scoop issue](https://github.com/ScoopInstaller/Scoop/issues/4460).

**Comment by RavenMacDaddy** [comment]
They've updated the naming scheme to not include "dev", but just a numbered order.

Here are a few examples of different builds:

![image](https://user-images.githubusercontent.com/67732686/140618749-a093221d-3892-47d6-b18f-69521b25edf9.png)

... and here's a row of these numbered builds with the corresponding name of the dir as seen above:

![image](https://user-images.githubusercontent.com/67732686/140618765-fb1eb67d-7951-471f-a9db-ccbdeef08c22.png)

**Comment by mnxn** [comment]
I just noticed this too.
The `checkver` and `autoupdate` sections need to have their regular expressions and replacements updated.

I will try to create a PR within the next few days.
