### ISSUE TITLE
Updated dgVoodoo2 pull request

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#493]
Regarding #237.

This pull request has now been updated to the latest version at the time of writing.

Even if I did it 8 months ago when I just started to learn manifests, updating the links and hashes was about the only thing I'd to do - kinda surprised to be honest.

Would be great if you could check it out and thank you for your time.

For reference I've tested installation by creating the same manifest on my own repo first and autoupdate should be okay, but correct me if I'm wrong.

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/scoop-games/pull/237. Thanks for your work :slightly_smiling_face:
