### ISSUE TITLE
cemu@1.26.0c: Hash check failed

### ISSUE THREAD

**Issue by IsjaslawEisenstadt** [Calinou/scoop-games#500]
Hash check failed!
App:         games/cemu
URL:         https://cemu.info/releases/cemu_1.26.0.zip
First bytes: 80 75 3 4 10 0 0 0
Expected:    1783557ca60ae6b84cb114669ffb4f9b4db0ed1babc66bf1bacb15f2ce674fd6
Actual:      c5275a6ff31f4fa72ab45157156e2a74ed673156a57722ec32fb7278b0ac045c

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/scoop-games/commit/d479624f2fc3015344977de69f9ef33f812d119e.
