### ISSUE TITLE
project64@3.0.1: hash check failed

### ISSUE THREAD

**Issue by flythereddflagg** [Calinou/scoop-games#502]
output:
> scoop install project64
Installing 'project64' (3.0.1) [64bit]
setup-project64-3-0-0-5632-f83bee9 (4.2 MB) [=================================================================] 100%
Checking hash of setup-project64-3-0-0-5632-f83bee9 ... ERROR Hash check failed!
App:         games/project64
URL:         https://www.pj64-emu.com/file/setup-project64-3-0-0-5632-f83bee9/
First bytes: 4D 5A 50 00 02 00 00 00
Expected:    5892d6bef423076a103991c78690083a87536865ea848c0eccf2e4f94a64033b
Actual:      93f3db8dc5642d39fcc44eaf43811cdbdf912690f95041e924e038e76f36f921

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=project64%403.0.1%3a+hash+check+failed
>

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/scoop-games/issues/502. Thanks for the report :slightly_smiling_face:
