### ISSUE TITLE
Origin launcher

### ISSUE THREAD

**Issue by couleurm** [Calinou/scoop-games#503]
Found this old forum post, feel free to make it a working manifest if you want/use this issue as place to discuss about making origin manifest

https://answers.ea.com/t5/EA-General-Questions/Any-way-to-do-a-silent-quiet-install-of-Origin-10/td-p/5622110

**Comment by beyondmeat** [comment]
origin is deprecated in favor of their new ea app
its also not portable

**Comment by beyondmeat** [comment]
@Calinou  can close

**Comment by Calinou** [comment]
Closing, as I don't think packaging Origin within a Scoop manifest would work out well as @beyondmeat pointed.
