### ISSUE TITLE
m64p: persisting config data

### ISSUE THREAD

**Issue by redactedscribe** [Calinou/scoop-games#510]
[mupen64plus was recently added](https://github.com/Calinou/scoop-games/pull/450) to the bucket but there seems to be a problem as the "mupen64plus-gui.ini" file does not affect the program, i.e. running the program and looking under "Settings > Plugin and Path Selection" shows that "Config Dir Path" is set to `$CONFIG_PATH$` despite "mupen64plus-gui.ini" defining it as `$APP_PATH$/config`.

In this state, "input-profiles.ini", "input-settings.ini", and "mupen64plus.cfg" are saved to "%appdata%\Mupen64Plus" instead of the "config" dir in the program's directory (a directory which ["m64p.json" persists](https://github.com/Calinou/scoop-games/blob/master/bucket/m64p.json#L21)).

I have seen that after installing m64p via Scoop, a note message appears saying "Configuration files cannot be persisted, but will be retained during the update", however it should be possible to do:

The "configDirPath" value is stored in the registry (HKEY_CURRENT_USER\Software\mupen64plus\gui) and it reads `$CONFIG_PATH$`. Changing this value to `$APP_PATH$/config` causes the mentioned ini/cfg files to be stored in the persisted "config" dir. Therefore, if the manifest also set this registry value via `post_install` (["zoom.json" has an example](https://github.com/ScoopInstaller/Extras/blob/master/bucket/zoom.json#L23)) the configuration files would persist.

Setting the registry value may actually just be a workaround if it turns out that the problem is instead m64p not honouring the "mupen64plus-gui.ini" values.

manifest author: @satorope
m64p dev: @loganmc10

**Comment by loganmc10** [comment]
As you say, m64p stores the value of configDirPath in the registry, not in mupen64plus-gui.ini

mupen64plus-gui uses Qt, and it is using QSettings to store this data (https://github.com/m64p/mupen64plus-gui/blob/9cdadb37ab67d1b3bad615312fc792433f324c8c/mainwindow.cpp#L331)

QSettings uses the registry by default on Windows, and ~/.config/mupen64plus on Linux.

Past versions sorted the settings in mupen64plus-gui.ini, which was located in the same folder as mupen64plus-gui. However, the installation directory (where mupen64plus-gui.exe resides) is not always writeable, so it was changed to use the registry in order to make sure the location was always writeable

**Comment by redactedscribe** [comment]
To my knowledge, Scoop doesn't attempt to backup/save program settings which store to the registry, making persisting such settings not possible. An indirect solution could be to allow m64p to either store its Qt settings to the registry, or as before to "mupen64plus-gui.ini" in the case where the file is present in the program's directory (I assume it's the same format as the Linux file and so may not be too much work to reimplement). This way the program's settings, as well as its Qt settings, would be portable if desired, and too, fix this issue. Alternatively, we could write the "configDirPath" value to the registry as mentioned previously. Which approach depends on @loganmc10's answer I suppose.

**Comment by loganmc10** [comment]
I fixed the issue: https://github.com/loganmc10/m64p/commit/4ca0517ceef643dbd8860428d7e436b5b5e16d27

It will attempt to write mupen64plus-gui.ini, and if it is not writeable, it will fall back to using the registry. That change will make it in to the next version of m64p, but I don't have a date for that yet

**Comment by redactedscribe** [comment]
Great! I assume the Windows version will also attempt to read the ini on program launch if the file is present?

**Comment by loganmc10** [comment]
If it's in the same directory as the EXE, yes

**Comment by redactedscribe** [comment]
Perfect. Thanks @loganmc10!

Assuming the fix works, this issue can be closed once a m64p version greater than "2021.12.29" is released.

**Comment by beyondmeat** [comment]
@redactedscribe close
