### ISSUE TITLE
Add Pegasus Frontend

### ISSUE THREAD

**Issue by kewalsky** [Calinou/scoop-games#518]
[Pegasus](https://pegasus-frontend.org) is a frontend launcher for game emulators (such as those currently in bucket)
- Files are distributed via [GitHub](https://github.com/mmatyas/pegasus-frontend/releases)
- Placing "portable.txt" in the application root will cause it to run in portable mode ([docs](https://pegasus-frontend.org/docs/user-guide/portable/))
- Portable mode configuration files are located in "/config" in the applcation root ([docs](https://pegasus-frontend.org/docs/user-guide/config-dirs/))
- Possible manifest would create and persist the portable.txt and config folder

**Comment by kewalsky** [comment]
this might also be more fitted for Scoop Extra, not confident on which one it fits in better

**Comment by Zliced13** [comment]
Done in #711
