### ISSUE TITLE
Mindustry (client)

### ISSUE THREAD

**Issue by Luckz** [Calinou/scoop-games#56]
As requested in https://github.com/Calinou/scoop-games/issues/24 , https://github.com/Calinou/scoop-games/pull/27 brought Mindustry to scoop. 
However, a) the json hasn't been updated in quite some time (the server binary has been)
b) it would maybe make more sense to provide the client via [Windows-64bit]Mindustry.zip from https://anuke.itch.io/mindustry ?
I don't know if direct linking to itch.io downloads is a thing though..

**Comment by r15ch13** [comment]
Fixed and updated mindustry.
itch.io downloads seem to be session-based, which is currently not supported by scoop.
But the only contain a java environment and an exe that just runs the same `Mindustry.jar` file.
