### ISSUE TITLE
cemu@1.26.2e: hash check failed

### ISSUE THREAD

**Issue by ricardobsp** [Calinou/scoop-games#561]
Updating 'cemu' (1.26.1 -> 1.26.2e)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: 230fb7|OK  |   6.8MiB/s|D:/Scoop/cache/cemu#1.26.2e#https_cemu.info_releases_cemu_1.26.2.zip
Download: Status Legend:
Download: (OK):download completed.
Checking hash of cemu_1.26.2.zip ... ERROR Hash check failed!
App:         games/cemu
URL:         https://cemu.info/releases/cemu_1.26.2.zip
First bytes: 50 4B 03 04 0A 00 00 00
Expected:    58f51f98ee40c6c39ebb849f6534aaf66416dc47214c569fc5f72d9a7b4d0280
Actual:      b0e3abf5048f78e352b42c3e1660a2c6e85d6905cd9f60d06ca2f2318fa3152c

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/scoop-games/commit/1fe4010f8c88dcacc58185583b8fc54016ad5a31.
