### ISSUE TITLE
Xemu not updating in repo

### ISSUE THREAD

**Issue by beyondmeat** [Calinou/scoop-games#573]
I've been trying to figure this out for a few days now and I'm stumped. For some reason, this bucket isn't applying auto-updates to xemu.

When I run ./bin/checkver.ps1 xemu it returns the new version and shows update available. I checked the urls, etc. everything looks good. It installs fine. My guess is the PR bot is skipping xemu or excluding it from it's runs.

@Calinou can you take a quick look please

**Comment by beyondmeat** [comment]
@r15ch13 please check your end

**Comment by r15ch13** [comment]
https://scoop.r15.ch/games/mud-20220301-003001.log
```
xemu: couldn't match 'gh-release%2F(.+)/xemu-win-release\.zip' in https://api.github.com/repos/mborgerson/xemu/releases/latest
```
The regex is not matching

**Comment by beyondmeat** [comment]
@r15ch13 thanks knew it was something small like that.
