### ISSUE TITLE
rpcs3-dev manifest is missing

### ISSUE THREAD

**Issue by ompadu** [Calinou/scoop-games#599]
hi, it seems that the manifest for `rpcs3-dev` is missing, is it supposed to? 

thanks

**Comment by Calinou** [comment]
There is https://github.com/Calinou/scoop-games/blob/master/bucket/rpcs3.json already, is there a separate development version?

**Comment by beyondmeat** [comment]
rpcs3 only does rolling releases., there is no separate "stable" or "dev" version. Thus there is no need for `-dev` as it would be redundant in this case.

use `rpcs3` and move your persist data over.

**Comment by ompadu** [comment]
@Calinou it was at one point, but the manifest was removed. 

@beyondmeat thanks!
