### ISSUE TITLE
tesseract-game@nightly: download via aria2 failed

### ISSUE THREAD

**Issue by mdmundo** [Calinou/scoop-games#615]
ERROR Download failed! (Error 1) An unknown error occurred
ERROR http://mappinghell.net/tesseract/tesseract-nightly.zip
    referer=http://mappinghell.net/tesseract/
    dir=C:\Users\Edmundo\scoop\cache
    out=tesseract-game#nightly-20220507#http_mappinghell.net_tesseract_tesseract-nightly.zip

ERROR & 'C:\Users\Edmundo\scoop\apps\aria2\current\aria2c.exe' --input-file='C:\Users\Edmundo\scoop\cache\tesseract-game.txt' --user-agent='Scoop/1.0 (+http://scoop.sh/) PowerShell/5.1 (Windows NT 10.0; Win64; x64; Desktop)' --allow-overwrite=true --auto-file-renaming=false --retry-wait=2 --split=5 --max-connection-per-server=5 --min-split-size=5M --console-log-level=warn --enable-color=false --no-conf=true --follow-metalink=true --metalink-preferred-protocol=https --min-tls-version=TLSv1.2 --stop-with-process=12340 --continue --summary-interval=0 --auto-save-interval=1

**Comment by Calinou** [comment]
The download URL appears to be working again.
