### ISSUE TITLE
cemu@1.26.2f: install error - access to settings.xml is denied

### ISSUE THREAD

**Issue by ricardobsp** [Calinou/scoop-games#623]
I got an error on cemu install. The app is installed despite the error, but I believe settings.xml is incorrect. 
It created a folder called settings.xml instead of a file, inside persist folder.

Log: 

Installing 'cemu' (1.26.2f) [64bit]
Loading cemu_1.26.2.zip from cache.
Checking hash of cemu_1.26.2.zip ... ok.
Extracting cemu_1.26.2.zip ... done.
Running installer script...
Linking ~\scoop\apps\cemu\current => ~\scoop\apps\cemu\1.26.2f
Creating shim for 'Cemu'.
Creating shortcut for Cemu (cemu.exe)
Persisting settings.xml
Persisting controllerProfiles
Persisting gameProfiles
Persisting graphicPacks
Persisting mlc01
Persisting sharedFonts
Persisting shaderCache\transferable
Persisting keys.txt
Running post-install script...
New-Item:
Line |
   5 |         New-Item -ItemType File "$dir\$_" | Out-Null
     |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Access to the path 'C:\Users\ricar\scoop\apps\cemu\current\settings.xml' is denied.
'cemu' (1.26.2f) was installed successfully!
'cemu' suggests installing 'cemuhook'.
'cemu' suggests installing 'extras/vcredist2015'

**Comment by Calinou** [comment]
cc @beyondmeat

**Comment by ricardobsp** [comment]
This PR fixed it for me:

#638
