### ISSUE TITLE
Fix ares bot updater

### ISSUE THREAD

**Issue by ppvnf** [Calinou/scoop-games#635]
ares: Update to version 128 is not working. I guess you simply have to change line 13 to: "extract_dir": "ares-v128"

https://github.com/Calinou/scoop-games/commit/46a78d0a71e09583afb299db99f62da30c1953c0

**Comment by Calinou** [comment]
I don't have access to my PC currently, so feel free to open a pull request for this 🙂

**Comment by ppvnf** [comment]
I wonder

**Comment by Calinou** [comment]
> I wonder if the next ares update will have the same issue

I suggest modifying the `autoupdate` field to add an `extract_dir` line to it with a `$version` placeholder.

**Comment by Calinou** [comment]
cc @satorope, as they wrote the initial manifest for ares.

**Comment by ppvnf** [comment]
I barely know what I'm doing, but maybe a couple brackets will solve the problem

**Comment by issaclin32** [comment]
https://github.com/Calinou/scoop-games/pull/637#issuecomment-1154766405
