### ISSUE TITLE
minecraft@java-edition: hash check failed

### ISSUE THREAD

**Issue by tronics22** [Calinou/scoop-games#64]
Sorry, once more a mismatch of the md5 check...

Best regards,
Werner

Scoop was updated successfully!
Installing 'minecraft' (java-edition) [64bit]
Minecraft.exe (2.1 MB) [================================================================] 100%
Checking hash of Minecraft.exe ... ERROR Hash check failed!
App:         games/minecraft
URL:         https://launcher.mojang.com/download/Minecraft.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    22954f65c6ea85374c7af7ec4cd617b022044a31445b1dc4dede3129fd5d4920
Actual:      a541356a3103201145eac713c3a056674253634d895810b249f87d2d7a654d17

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Calinou/scoop-games/issues/new?title=minecraft%40java-edition%3a+hash+check+failed

**Comment by Calinou** [comment]
Should be fixed by https://github.com/Calinou/scoop-games/commit/31c42504a17dc0ed3bcce822c11fc3e782e20095.
