### ISSUE TITLE
MultiMC : Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by sebastien46** [Calinou/scoop-games#659]
So I was trying to install MultiMC but then I got this error : 
```
multimc
Installing 'multimc' (0.6.14) [64bit]
The request was aborted: Could not create SSL/TLS secure channel.
URL https://files.multimc.org/downloads/mmc-stable-win32.zip is not valid
```

when I go to this url in my browser it successfully downloads the file, what could possibly be happening ?

**Comment by sebastien46** [comment]
#511

**Comment by Calinou** [comment]
This is an issue with your Scoop client: https://github.com/ScoopInstaller/Install/issues/27

**Comment by sebastien46** [comment]
Alright, haven't been able to fix this issue, but since I have a modified windows install I believe this is indeed a misconfigured network component in my os. Thank you for helping me identify the issue :)
