### ISSUE TITLE
Discussion: How do we build a manifest for the SEGA Model 3 emulator Supermodel (uses random string for builds)?

### ISSUE THREAD

**Issue by RavenMacDaddy** [Calinou/scoop-games#681]
Here's an example of a download URL: https://supermodel3.com/Files/Git_Snapshots/Supermodel_0.3a-git-a60f998_Win64.zip

So the `a60f998` portion is what changes with each release to another random string.

The [repository itself](https://supermodel3.com/Files/Git_Snapshots/) has nice dated releases, that part should be easy to figure out - the random string is the issue.

I wonder if what's used in [this manifest](https://github.com/ScoopInstaller/Extras/blob/fccdc94140356911d62a6a7dd5b761bec9bc7671/bucket/mobaxterm.json) would work?

**Comment by BlackPowerade** [comment]
`git-(?'hash'[\da-z]+)_Win64.zip`     
This should produce a hash capture group for use in the manifest.

**Comment by RavenMacDaddy** [comment]
Great start!

Now the question, how do we specify a regex that covers both the date in the repository - as well as the hash of the download?

**Comment by BlackPowerade** [comment]
That's a good question. I'm not sure.     
I've tried `-(?'hash'[\da-z]+)_Win64\X*?(?'date'[\d\-]{10})` which should work.   
But, it comes with multiple matches and scoop doesn't understand the `\X`.       
I don't know how to make it work right now.     
Also you will need to use `https://supermodel3.com/Files/Git_Snapshots/?C=M;O=D` for the checkver URL. I don't know what the default sorting is on the page, but it is not by date.

**Comment by RavenMacDaddy** [comment]
Ah, so even if the date is specified, it doesn't matter because it's out of order; Scoop needs everything to fall in place sorted and doesn't "count up the date"?

**Comment by BlackPowerade** [comment]
Yes, if I remember correctly checkver.ps1 picks up the first (or it might be last) regex match for determining if an update is available.      
I'm also taking a shot at setting up a github actions flow for compiling supermodel, but I can't get the windows builds to work, mingw and make can't find SDL. Maybe the repo owners would be willing to take a look at it? Would definitely be better than the python script right now used to push new builds to the website. https://github.com/trzy/Supermodel/blob/master/Scripts/supermodel_build_bot.py

**Comment by RavenMacDaddy** [comment]
Created a post over on their repo.
