### ISSUE TITLE
xenia-canary is out of date

### ISSUE THREAD

**Issue by ppvnf** [Calinou/scoop-games#717]
Latest version: https://github.com/xenia-canary/xenia-canary/releases/tag/experimental

**Comment by ppvnf** [comment]
Someone recommended me this bucket and I found xenia-canary in it: https://github.com/hermanjustnu/scoop-emulators/blob/master/bucket/xenia-canary.json

**Comment by BlackPowerade** [comment]
[https://github.com/xenia-canary/xenia-canary/releases.atom](https://github.com/xenia-canary/xenia-canary/releases.atom)?    
That's amazing. I wish I knew this file existed earlier, this could solve so many versioning issues its not even funny.    
I'll take a crack at this later on, but I might just copy the autoupdate. Might just use the git hash for the user presented version.    
Definitely going to take a look at some older manifests later on.
