### ISSUE TITLE
Request (CRITICAL): freeze PolyMC updates as the maintainer's account has been compromised

### ISSUE THREAD

**Issue by otavio-silva** [Calinou/scoop-games#720]
The PolyMC main dev [LennyMcLennington](https://github.com/PolyMC/PolyMC/commits?author=LennyMcLennington) has (probably) been hacked. The Discord server, the website, the [repo](https://github.com/PolyMC/PolyMC) on GitHub is all compromised. Since PolyMC stores the Microsoft/Mojang account and has certain permissions, I believe this issue is very relevant at the moment.

**Comment by Steveplays28** [comment]
Thank you. A fork is being made called [PlaceholderMC](https://github.com/PlaceholderMC/PlaceholderMC)

**Comment by comicsansgreenki** [comment]
From what I'm hearing in the discord server set up, we may be dropping PolyMC entirely.

**Comment by TayouVR** [comment]
does scoop have some way to migrate people from one package to another?
New packages for the fork/continuation PrismLauncher will need to be made as soon as a new release build and the rebranding is complete.
(All active maintainers and contributers are part of the fork, Only lenny is left with the old name, discord and gihtub org / repos)

Repo for reference: https://github.com/PrismLauncher/PrismLauncher

**Comment by Calinou** [comment]
`prismlauncher` and `prismlauncher-qt5` can now be installed. I'll keep this issue pinned for a few weeks as a migration notice.
