### ISSUE TITLE
Request: Add Prism Launcher

### ISSUE THREAD

**Issue by osfanbuff63** [Calinou/scoop-games#721]
As a result of #720, much of the team that once made PolyMC has made [PrismLauncher](https://github.com/PrismLauncher/PrismLauncher). As of a few minutes ago, they have made the first versioned release, [5.0](https://github.com/PrismLauncher/PrismLauncher/releases/5.0) (inherited from PolyMC). [Here's a direct portable download link](https://github.com/PrismLauncher/PrismLauncher/releases/download/5.0/PrismLauncher-Windows-Portable-5.0.zip).

This issue basically serves as a (potentially unneeded) successor to #720, but it's probably big enough that it can get its own issue. I mean, 1.2k stars and 77 forks in 2 days is quite impressive 😅

**Comment by Calinou** [comment]
Feel free to open a pull request for this :slightly_smiling_face:

**Comment by Calinou** [comment]
This was implemented by https://github.com/Calinou/scoop-games/pull/723, closing.
