### ISSUE TITLE
Prisma manifest

### ISSUE THREAD

**Issue by rafalohaki** [Calinou/scoop-games#725]
- PS C:\Users\Admin> scoop install prismlauncher
- Couldn't find manifest for 'prismlauncher'.
- PS C:\Users\Admin> scoop bucket add games
- WARN  The 'games' bucket already exists. To add this bucket again, first remove it by running 'scoop bucket rm games'.

**Comment by Calinou** [comment]
https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json
https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher-qt5.json

Try running `scoop update *` First.

Also, does it work if you use `scoop install prismlauncher-qt5`? Also, what does `scoop search prismlauncher` return?

**Comment by rafalohaki** [comment]
- Scoop was updated successfully!
- PS C:\Users\Admin> scoop update *
- Latest versions for all apps are installed! For more information try 'scoop status'
- PS C:\Users\Admin> scoop status
- WARN  Scoop bucket(s) out of date. Run 'scoop update' to get the latest changes.
- PS C:\Users\Admin> scoop search prismlauncher
- WARN  No matches found.

**Comment by rafalohaki** [comment]
- PS C:\Users\Admin> scoop install https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z
- WARN  Error parsing JSON at https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z.
- WARN  Bucket 'https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z' not installed. Add it with 'scoop bucket add https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z' or 'scoop bucket add https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z <repo>'.
- Couldn't find manifest for 'prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z' from 'https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A51%3A58Z' bucket.

**Comment by Calinou** [comment]
> WARN Error parsing JSON at [master/bucket/prismlauncher.json](https://github.com/Calinou/scoop-games/blob/master/bucket/prismlauncher.json?rgh-link-date=2022-10-24T19%3A57%3A42Z).

I've checked the JSON's validity using [this tool](https://jsononline.net/json-validator) and both `prismlauncher.json` and `prismlauncher-qt5.json` appear to be valid.

**Comment by rafalohaki** [comment]
> 

is it working for you? i mean scoop install prismlauncher

**Comment by anderlli0053** [comment]
@rafalohaki  It does work for me, maybe try to re-add games repo? For me it works something like this:  `scoop bucket rm games && scoop bucket add games` or even maybe add the actual link to the repository after the name alias..?, like so: `scoop bucket rm games && scoop bucket add games https://github.com/Calinou/scoop-games.git`  even though it should register automatically without the need for doing that, as the games bucket is one of the official ones and built-in..

**Comment by anderlli0053** [comment]
@rafalohaki  If it does not work, run `scoop bucket list` and see how is the games bucked aliased as and what value it has for its repo: 

![1123](https://user-images.githubusercontent.com/22171451/198152320-1f058327-a926-47f8-a4d4-21c818e2e0af.jpg)

**Comment by rafalohaki** [comment]
i did `scoop bucket rm games && scoop bucket add games` and its working now
