### ISSUE TITLE
Add TLauncher

### ISSUE THREAD

**Issue by anderlli0053** [Calinou/scoop-games#728]
**Official website:** https://tlauncher.org/en/
**Developer:** TLauncher team
**Description:** Popular launcher for Minecraft game
**Download link:** https://dl2.tlauncher.org/f.php?f=files%2FTLauncher-2.86-Installer-1.0.1.exe

**Comment by Calinou** [comment]
TLauncher allows playing Minecraft without having bought the game from Mojang (which is an EULA violation), so I'm afraid it's a no-go for inclusion in scoop-games.

**Comment by anderlli0053** [comment]
> 

Oh well, at least i tried 😆 , thanks anyway
