### ISSUE TITLE
Add AlecaFrame

### ISSUE THREAD

**Issue by anderlli0053** [Calinou/scoop-games#729]
**Official website:** https://www.alecaframe.com/
**Developer:** Alejandro Cabrerizo
**Description:** The most advanced WarFrame companion app for PC
**Download page:** https://www.alecaframe.com/

**Comment by Zliced13** [comment]
@anderlli0053 There is no separate installer for this, it depends on OverWolf.

**Comment by Zliced13** [comment]
Also, OverWolf has no silent installation switch.

**Comment by anderlli0053** [comment]
Sadly...ok, so should this be closed then?

**Comment by Zliced13** [comment]
Yes it should be closed.
