### ISSUE TITLE
(Request) add GOG-Galaxy 2.0

### ISSUE THREAD

**Issue by dtantono** [Calinou/scoop-games#736]
PackageIdentifier: GOG Galaxy
PackageVersion: 2.0
PackageLocale: en-US
Publisher: GOG
PackageName: GOG-Galaxy
License: proprietary
ShortDescription: GOG client
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://webinstallers.gog-statics.com/download/GOG_Galaxy_2.0.exe?payload=Jp6nwB9LMmMEwj2QUaoZLbW3ISUJOMsL9bX03lNo00v-bxdzwZHq2Ht0P2F4G7oGd3GtX9kc59hFOtvC6pfj8jxfD0tgPoNF9vsOZfZKP44JeMF4_9OpK7OA5Xa_jrxV2rR0pGRV2iNIh4mRMxQsXGAeI_XYeTE3IK_s5ebjPjUpxDb4onIfJiTOmbrBw6zd19h6Unn1khnysB05rS1YRdjd8SByIbA1uGvv5lbZQ7zpKDL5h-5hSdsss8tYLnEvNyAZ74GYeZXKhp_6hf9wJfncdVCZCJUid_w9LgMj__JqiTVgmuaEYOiZRuEeawYqEs7jC1VJdIHl7Fhp0w2dwwrhpZg5VZrVYTn9XtMBL8IL3mc_zqYI3NQm28iWCEYJWRW97Ie4ZkAa9JxFU7tGTNAMPPaZfFwIF2OjVqE1qNctwnjKkJDVF37h5fdy9DRQYNWIPetNvuLdAaaG4b3ycHcILzMGRgLTkbRcq0e1r-uKm1RvSfvqvgMMt17OpumrfZ5Q43JUU0VLQtsX5zYBjaDVwve4IZnVWl0w9pUi2RJRzdhXA1KW9qgZRZuJVyY4hjttiwH0mq0G7VJqV9SNiKzCDiU3poq0p9zWGaUgAmTUph9ARPWNfS_jFMl8b-Jx41DQGdBkxHIH4MjO-u3Iyit14Qvf2SIyE72Otb2CG4P8Aw..
ManifestType: singleton
ManifestVersion: 1.0.0

**Comment by Ciberbago** [comment]
Hi! I thank you for all your effort, but I'm facing a problem. I refer to it in this issue #907
