### ISSUE TITLE
Cemu 2.0 is experimental

### ISSUE THREAD

**Issue by eboddington** [Calinou/scoop-games#744]
The version of Cemu installed by this bucket is 2.0, which is currently an experimental pre-release and is not considered stable. Is this deliberate? It'd be nice for it to install the latest stable 1.x instead

**Comment by beyondmeat** [comment]
They just haven't updated the site yet but on github there is no longer marked experimental on the 2.0 tag. 

It's probable that a 2.0.x will be marked "stable" soon as well.
At this point it doesn't make sense to change it.

There is also 1.27 old experimental version in-between 1.26 and 2.0

Is there a compelling reason to keep using 1.26 over 2.0?

**Comment by eboddington** [comment]
> Is there a compelling reason to keep using 1.26 over 2.0?

I've only really been playing Breath of the Wild, but for me it crashed every time I reached a very early cutscene with 2.0, whereas 1.26 has been completely stable.

> They just haven't updated the site yet but on github there is no longer marked experimental on the 2.0 tag.

Looking at their GitHub releases, I can see the original `2.0` release from August but as far as I can tell, that was released when the [2.0 announcement post](https://www.reddit.com/r/cemu/comments/wwa22c/cemu_20_announcement_linux_builds_opensource_and) was made, which states that it should be considered experimental. Every release since then has been explicitly marked experimental.

> It's probable that a 2.0.x will be marked "stable" soon as well.

Do you have a source for this? The original announcement described it as a big change, so without further information I'd guess that it might also take a while.

> I suppose we could make cemu.json point to the latest 1.x release, but this will break existing installations of the "stable" package

Ahh, this is very true though. Maybe there's not much that can be done right now then apart from wait for a stable 2.0 release soon.

**Comment by beyondmeat** [comment]
@eboddington They orginally marked the 2.0 release as experimental on github, but changed it. github would be the best source of truth over the site, which the devs don't update as often.

if you want to use cemu 1.x, you can install cemu from this bucket: https://github.com/borger/scoop-emulators
I maintain that repo and the same manifests in this repo.

Have you tried the latest 2.0.x release to see if it crashes? the latest 2.0.x release is listed as cemu-dev in that bucket.

I recommend trying the latest 2.0.-17 release since it's just bug fixes and improvements to 2.0.

As for my source: I follow their development on github and discord and discussions with the dev team, also being a dev myself.

**Comment by beyondmeat** [comment]
@Calinou I can bring over cemu-dev which has the latest 2.0 release (which I recommend over 2.0 since it's just bugfixes).

It's kind of a rock and a hard place with cemu.json right now. You will have ppl upset no matter what you do.

**Comment by Calinou** [comment]
Feel free to open a PR to update cemu-dev :slightly_smiling_face:

**Comment by eboddington** [comment]
@beyondmeat ok, fair enough. I haven't installed the latest release to be fair, so perhaps it's sorted in that. Agree that not much can be done to sort out `cemu.json` now, and personally I will probably stay on my manual installation until 2.x is officially declared stable and available here, and then switch back to that. It's working fine, no reason for me to switch to 2.x yet personally.

**Comment by Calinou** [comment]
I think it's best to keep things as they are now.
