### ISSUE TITLE
ryujinx-ava installation fails

### ISSUE THREAD

**Issue by kartikynwa** [Calinou/scoop-games#781]
Output:

```
❯ scoop install ryujinx-ava
Installing 'ryujinx-ava' (1.1.518) [64bit] from games bucket
Loading test-ava-ryujinx-1.1.518-win_x64.zip from cache.
Checking hash of test-ava-ryujinx-1.1.518-win_x64.zip ... ok.
Extracting test-ava-ryujinx-1.1.518-win_x64.zip ... done.
Running pre_install script...
Linking ~\scoop\apps\ryujinx-ava\current => ~\scoop\apps\ryujinx-ava\1.1.518
Creating shim for 'Ryujinx.Ava'.
Can't shim 'Ryujinx.Ava.exe': File doesn't exist.
```

I think the problem is that the executable is named `Ryujinx.exe` and there is no file named `Ryujinx.Ava.exe`. Want me to file a PR to fix this? Should be a simple change in the manifest.

**Comment by Calinou** [comment]
> Want me to file a PR to fix this? Should be a simple change in the manifest.

Sure :slightly_smiling_face:

**Comment by kartikynwa** [comment]
Looks like the binary name is back to being Ryujinx.Ava.exe. No action needed.
