### ISSUE TITLE
multimc download link has changed

### ISSUE THREAD

**Issue by littleboot** [Calinou/scoop-games#822]
The recommended according to the [wiki](https://github.com/MultiMC/Launcher/wiki/Getting-Started) 
https://files.multimc.org/downloads/mmc-develop-win32.zip

this link does not contain a version number, and seems to point to a developer realease.
I propose using the stable realeases on [github](https://github.com/MultiMC/Launcher/releases):

https://github.com/MultiMC/Launcher/archive/refs/tags/0.6.14.zip

**Comment by Calinou** [comment]
Feel free to open a pull request to use a stable tag :slightly_smiling_face:

**Comment by littleboot** [comment]
> Feel free to open a pull request to use a stable tag 🙂

Sure I will have a look at it. (Never did that before, I'm also new to scoop. But I think I will be able to figure this one out)🙃

**Comment by RuiNtD** [comment]
MultiMC doesn't do stable releases anymore:
https://multimc.org/posts/0-7-0-update.html
> With this, we are also abandoning the concept of stable releases. From now on, MultiMC will always use the `develop` channel.

**Comment by RuiNtD** [comment]
For anyone still here, you can just use `prismlauncher` instead.

**Comment by Calinou** [comment]
- Closing in favor of https://github.com/Calinou/scoop-games/issues/861.
