### ISSUE TITLE
[Bug]: multimc issue with Cloudflare

### ISSUE THREAD

**Issue by RuiNtD** [Calinou/scoop-games#861]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

multimc

### Expected/Current Behaviour

MultiMC's stable download link (which isn't being supported by its devs anymore) is currently being false flagged by Cloudflare as a phishing link. The bot is currently [having the time of its life](https://i.imgur.com/voxzuzB.png) updating MultiMC's hash, since the Cloudflare error page being downloaded has a constantly changing Cloudflare Ray ID in the HTML.

### Steps to Reproduce

```console
Refusing to include the error, so the bot doesn't mistakenly flag this issue as a simple hash issue.
```

### Possible Solution

Either:
1. Remove the `multimc` package
2. Replace the download with the develop link and rely on the GitHub bot handling issues to keep the constantly updating static link up to date. 

### Scoop and Buckets Version

```console
PS> scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
41183f8c1 (HEAD -> master, origin/master, origin/HEAD) vscodium: Update to version 1.77.0.23090

'games' bucket:
76c87eab (HEAD -> master, origin/master, origin/HEAD) multimc@0.6.14: Fix hash (Closes #859)

'java' bucket:
b94e23bd (HEAD -> master, origin/master, origin/HEAD) openjdk21: Update to version 21-16-ea

'main' bucket:
51a980933 (HEAD -> master, origin/master, origin/HEAD) syft: Update to version 0.76.0

'nerd-fonts' bucket:
58f791f (HEAD -> master, origin/master, origin/HEAD) Font-Awesome: Update to version 6.4.0

'nirsoft-alternative' bucket:
4a092e7 (HEAD -> master, origin/master, origin/HEAD) Update url list [ci skip]
```

### Scoop Config

```console
PS> scoop config

last_update          aria2-enabled scoop_branch scoop_repo
-----------          ------------- ------------ ----------
3/31/2023 1:13:32 PM         False master       https://github.com/ScoopInstaller/Scoop
```

### PowerShell Version

```console
PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.3
PSEdition                      Core
GitCommitId                    7.3.3
OS                             Microsoft Windows 10.0.23419
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by Calinou** [comment]
Thanks for the report! Consolidating in https://github.com/Calinou/scoop-games/issues/660, as this is due to the same cause.

**Comment by SandeMC** [comment]
Why is this still pinned? @Calinou

**Comment by Calinou** [comment]
> Why is this still pinned? @Calinou

I left it pinned by mistake. It's unpinned now :slightly_smiling_face:
