### ISSUE TITLE
[Bug]: yuzu-pineapple: `Remove-Item` errors when migrating "$env:APPDATA\yuzu"

### ISSUE THREAD

**Issue by soredake** [Calinou/scoop-games#870]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

yuzu-pineapple

### Expected/Current Behaviour

When i tried installing yuzu-pineapple i got this:
[yuzu-pineapple-log.txt](https://github.com/Calinou/scoop-games/files/11239485/yuzu-pineapple-log.txt)

Yuzu save directory is synchronized to Google Drive, maybe this caused permission errors.

### Steps to Reproduce

```console
1) Have "$env:APPDATA\yuzu" with yuzu data
2) Sync "$env:APPDATA\yuzu\nand\user\save" to google drive
3) scoop install yuzu-pineapple

Log: https://gist.github.com/soredake/6e5642f2437c65ac678a1f5025abd611
```

### Possible Solution

I don't know.

### Scoop and Buckets Version

```console
❯ scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
34e05d078 (HEAD -> master, origin/master, origin/HEAD) cryptomator: Add `nonportable/winfsp-np` as a suggestion (#10922)

'games' bucket:
26270704 (HEAD -> master, origin/master, origin/HEAD) yuzu-pineapple: Update to version EA-3512

'main' bucket:
f04ca5407 (HEAD -> master, origin/master, origin/HEAD) nano: Update to version 7.2-22.1
```

### Scoop Config

```console
❯ scoop config

last_update         scoop_repo                              scoop_branch
-----------         ----------                              ------------
15.04.2023 15:18:06 https://github.com/ScoopInstaller/Scoop master
```

### PowerShell Version

```console
❯ echo $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.3.2
PSEdition                      Core
GitCommitId                    7.3.2
OS                             Microsoft Windows 10.0.22621
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by soredake** [comment]
@sti1l-0

**Comment by sti1l-0** [comment]
The script is going to **move** your save data from your **$APPDATA** path to the **presist** path of yuzu. You loose your permision since other software is controlling the folder.
I don't think that's a bug but a kind of conflict. You have may way to solve it yourself.
