### ISSUE TITLE
Adding OpenMW

### ISSUE THREAD

**Issue by apommel** [Calinou/scoop-games#94]
OpenMW is a popular Open Source reimplementation of The Elder Scrolls III: Morrowind engine, and is still under heavy development (you can check out their [github](https://github.com/OpenMW/openmw)).

I tried to write [a manifest](https://github.com/apommel/scoop-bucket-build/blob/master/openmw.json) to make your work easier, but I don't know how to deal with persist data (saves and configuration files), which seems to be currently hardcoded to go to `C:\Users\username\Documents\My Games\OpenMW` ([ref1](https://forum.openmw.org/viewtopic.php?t=5097), [ref2](https://forum.openmw.org/viewtopic.php?f=2&t=3402#p38007)), so you can take my manifest as a reference but if you can improve that it would be great. Also I currently added the same shortcuts as their installer, but it may be a lot, I'm not sure. Also, the entire installer content is currently extracted but some parts are not useful (installer data in `$PLUGINSDIR` and uninstaller executable), I don't know if that would be an issue.

Also it would be nice to have an `openmw-nightly` app as the nightlies are actually used a lot (they are available [here](https://forum.openmw.org/viewtopic.php?t=1808) along with their hash), but I don't know how to deal with the versioning.

Thanks in advance!

**Comment by Calinou** [comment]
> I tried to write a manifest to make your work easier, but I don't know how to deal with persist data (saves and configuration files), which seems to be currently hardcoded to go to C:\Users\username\Documents\My Games\OpenMW (ref1, ref2), so you can take my manifest as a reference but if you can improve that it would be great.

If the application saves its data outside the program directory, then you don't need to do anything specific to handle it :slightly_smiling_face:

**Comment by apommel** [comment]
I believe the pull request resolved this issue!
