### ISSUE TITLE
[Request]: PKHeX

### ISSUE THREAD

**Issue by superusercode** [Calinou/scoop-games#954]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used
- [X] A game or a game-related tool
- [X] English interface (or at least English documentation)
- [X] Latest stable or development version
- [X] Full version (i.e. not a trial version)
- [X] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

PKHeX

### Description

Pokémon core series save editor, programmed in C#.

### Homepage

https://projectpokemon.org/home/files/file/1-pkhex/

### Download Link(s)
https://dlhb.gamebrew.org/3dshomebrews/pkhex.7z

### Some Indication of Popularity/Repute

https://github.com/kwsch/PKHeX 2.9k stars

**Comment by echizenryoma** [comment]
Please review.
