### ISSUE TITLE
[Request]: Dungeon Crawl Stone Soup

### ISSUE THREAD

**Issue by superusercode** [Calinou/scoop-games#962]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Reasonably well-known and widely used
- [X] A game or a game-related tool
- [X] English interface (or at least English documentation)
- [X] Latest stable or development version
- [X] Full version (i.e. not a trial version)
- [x] Fairly standard install (e.g. uses a version-specific download URL, no elaborate pre/post install scripts)

### Name

Dungeon Crawl Stone Soup

### Description

Dungeon Crawl Stone Soup is a game of dungeon exploration, combat and magic, involving characters of diverse skills, worshipping deities of great power and caprice. To win, you'll need to be a master of tactics and strategy, and prevail against overwhelming odds.

### Homepage

https://github.com/crawl/crawl

### Download Link(s)

https://github.com/crawl/crawl/releases/download/0.30.0/dcss-0.30.0-win32-tiles.zip

### Some Indication of Popularity/Repute

2k stars on github

**Comment by mundifex** [comment]
Already exists in Extras bucket as `stone-soup` and `stone-soup-tiles`. See #39.
