### ISSUE TITLE
[Bug]: ironwail.json faulty?

### ISSUE THREAD

**Issue by martiz** [Calinou/scoop-games#973]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

ironwail.json

### Expected/Current Behaviour

I didn't expect to have a warning/error message from the games bucket. This happened when I just simply search the scoop database. Thus the faulty ironwail.json file doesn't produce a proper manifest if inquiring a 'scoop info' command regarding to the game "ironwail".

Following error messages posted:
WARN  Error parsing JSON at C:\Users\Martin\scoop\buckets\games\bucket\ironwail.json.
Could not find manifest for 'ironwail' in local buckets.

### Steps to Reproduce

```console
PS> scoop search [anything]
WARN  Error parsing JSON at C:\Users\martiz\scoop\buckets\games\bucket\ironwail.json.

PS> scoop info ironwail
Could not find manifest for 'ironwail' in local buckets.
```

### Possible Solution

Deleting the 'ironwail.json' file in the aforementioned folder disables the warning message.
Till the next 'scoop update' command.

### Scoop and Buckets Version

```console
PS > scoop --version
Current Scoop version:
v0.3.1 - Released at 2022-11-15

'extras' bucket:
bf31c1b97 (HEAD -> master, origin/master, origin/HEAD) x64dbg: Update to version 2023-05-20_17-35

'games' bucket:
4b1f15ed (HEAD -> master, origin/master, origin/HEAD) xenia-canary: Update to version 20230520141201-ad2d27f

'java' bucket:
14b6eaa1 (HEAD -> master, origin/master, origin/HEAD) temurin8-nightly-jre: Update to version 8.0.382-2.0.202305191923

'main' bucket:
cb333da01 (HEAD -> master, origin/master, origin/HEAD) trid: Update to version 2.24-23.05.20

'nirsoft' bucket:
28db834 (HEAD -> master, origin/master, origin/HEAD) Excluded two pad files that require a password. They need to be updated manually.

'sysinternals' bucket:
952e2ec (HEAD -> main, origin/main, origin/HEAD) sysinternals-suite@2023.03.30: Fix hash (Closes #11)
```

### Scoop Config

```console
PS> scoop config

last_update                       aria2-warning-enabled scoop_branch scoop_repo
-----------                       --------------------- ------------ ----------
2023-05-20T20:59:37.1083860+02:00                 False master       https://github.com/lukesampson/scoop
```

### PowerShell Version

```console
PS> $psversiontable

Name                           Value
----                           -----
PSVersion                      5.1.19041.2673
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.2673
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Additional Softwares

None, even the game "ironwail" isn't installed because I've never heard of the game till now.

**Comment by Calinou** [comment]
Fixed by https://github.com/Calinou/scoop-games/commit/2122ac4ce9423fbb558a0f598181f109e6456773.

PS: I'm surprised Scoop is softlocked if any manifest contains invalid JSON. This sounds like a bug that should be resolved in Scoop.
